//! Code generation from the validated parameter model to truce sources.
//!
//! `Hawk2UI` defines parameters once — in the plugin manifest, surfaced as a
//! [`HawkManifest::parameter_model`](crate::HawkManifest::parameter_model) —
//! and this module emits the Rust `#[derive(Params)]` struct the truce DSP side
//! compiles. A sibling emitter (added once the editor runtime exposes a
//! parameter binding) will produce the editor-side TypeScript accessors from
//! the same model, so both sides stay addressable by the same parameter `u32`
//! through truce's `EditorBridge`.
//!
//! The emitter is pure string generation: it produces truce *source text* and
//! takes no dependency on `truce` itself, so it lives in `hawk2ui-build`
//! alongside the manifest and can be driven by the CLI without pulling in the
//! renderer or windowing stack. Verification that the emitted source actually
//! compiles against truce lives in `tests/param_codegen.rs`, which `include!`s
//! a checked-in golden produced by this emitter.
//!
//! All four parameter kinds are covered: continuous (`FloatParam`), integer
//! (`IntParam`), boolean (`BoolParam`), and indexed-choice (`EnumParam<E>` over
//! a generated `#[derive(ParamEnum)]` enum — one per choice parameter, emitted
//! ahead of the struct). Read-only meters become `#[meter] MeterSlot` fields.

use std::fmt::Write as _;

use hawk2ui_plugin::{
    EnumVariant, MeterRecord, ParameterDistribution, ParameterModel, ParameterRecord,
    ParameterValue,
};

/// Emits a truce `#[derive(Params)]` struct definition from `model`.
///
/// The returned source is self-contained — it carries its own `use` import —
/// and is intended to be written to a generated module in the author's plugin
/// crate, which depends on the `truce` umbrella crate. Parameters are emitted
/// in declaration order with explicit, declaration-order `id`s so the editor
/// side can address each parameter by the same `u32` through the
/// `EditorBridge`, rather than relying on truce's auto-assignment happening to
/// match.
#[must_use]
pub fn emit_truce_params_struct(struct_name: &str, model: &ParameterModel) -> String {
    let mut out = String::new();
    out.push_str("// Generated by hawk2ui from the plugin manifest. Do not edit by hand.\n\n");
    out.push_str("use truce::prelude::*;\n\n");

    // Indexed-choice parameters each need a `#[derive(ParamEnum)]` enum type in
    // scope before the `Params` struct references it as `EnumParam<E>`.
    for parameter in &model.parameters {
        if let ParameterValue::Choice(_) = parameter.default_value {
            emit_enum_type(&mut out, struct_name, parameter);
        }
    }

    out.push_str("#[derive(Params)]\n");
    let _ = writeln!(out, "pub struct {struct_name} {{");

    let mut next_id: u32 = 0;
    for parameter in &model.parameters {
        emit_param_field(&mut out, struct_name, next_id, parameter);
        next_id = next_id.saturating_add(1);
    }
    for meter in &model.meters {
        emit_meter_field(&mut out, meter);
    }

    out.push_str("}\n");
    out
}

/// Emits a single `#[param(...)]` field for `parameter` at `id`.
fn emit_param_field(out: &mut String, struct_name: &str, id: u32, parameter: &ParameterRecord) {
    let field = field_ident(&parameter.id);
    let (field_type, attrs) = field_spec(struct_name, id, parameter);
    let _ = writeln!(out, "    #[param({attrs})]");
    let _ = writeln!(out, "    pub {field}: {field_type},");
}

/// Emits a single `#[meter]` field. truce auto-assigns meter ids in a reserved
/// id space in declaration order, so no explicit id is emitted; the editor side
/// addresses meters by that same declaration order.
fn emit_meter_field(out: &mut String, meter: &MeterRecord) {
    let field = field_ident(&meter.id);
    let _ = writeln!(out, "    #[meter]");
    let _ = writeln!(out, "    pub {field}: MeterSlot,");
}

/// Emits a `#[derive(ParamEnum)]` enum type for an indexed-choice parameter,
/// one variant per model variant. The variant identifier is the `PascalCase`
/// of the variant id; a `#[name = "..."]` attribute carries the display name
/// whenever it differs from that identifier (truce's `ParamEnum::name`
/// otherwise returns the identifier).
///
/// Like the rest of the emitter, this trusts a validated model: a `Choice`
/// value always carries a non-empty, unique-id variant set, rejected upstream
/// otherwise by [`hawk2ui_plugin::ParameterModel::validate`] and the manifest
/// validator (which surface a diagnostic before emission, rather than letting
/// an uninhabited enum that would not compile reach the output).
fn emit_enum_type(out: &mut String, struct_name: &str, parameter: &ParameterRecord) {
    let type_name = enum_type_name(struct_name, &parameter.id);
    out.push_str("#[derive(ParamEnum)]\n");
    let _ = writeln!(out, "pub enum {type_name} {{");
    for variant in &parameter.variants {
        emit_enum_variant(out, variant);
    }
    out.push_str("}\n\n");
}

/// Emits one enum variant, with a `#[name = "..."]` override when the display
/// name differs from the derived `PascalCase` identifier.
fn emit_enum_variant(out: &mut String, variant: &EnumVariant) {
    let ident = pascal_ident(&variant.id);
    if variant.display_name != ident {
        let _ = writeln!(out, "    #[name = {:?}]", variant.display_name);
    }
    let _ = writeln!(out, "    {ident},");
}

/// Returns the truce field type and the `#[param(...)]` attribute body for a
/// parameter, branching on its typed value: continuous floats keep their
/// linear/logarithmic range, integers map to a discrete range, booleans carry
/// only an id/name/default (truce defaults a `BoolParam`'s range to
/// `Discrete{0,1}`), and an indexed choice becomes `EnumParam<E>` over the
/// per-parameter `#[derive(ParamEnum)]` type — truce infers the `Enum{count}`
/// range and the unit from that type, so only id/name/default-index are
/// emitted.
fn field_spec(struct_name: &str, id: u32, parameter: &ParameterRecord) -> (String, String) {
    let name = format!("{:?}", parameter.display_name);
    let unit = map_unit(&parameter.unit);
    match parameter.default_value {
        ParameterValue::Float(value) => (
            "FloatParam".to_string(),
            format!(
                "id = {id}, name = {name}, range = \"{}\", unit = \"{unit}\", default = {}",
                continuous_range(parameter),
                format_number(value),
            ),
        ),
        ParameterValue::Int(value) => (
            "IntParam".to_string(),
            format!(
                "id = {id}, name = {name}, range = \"{}\", unit = \"{unit}\", default = {value}",
                discrete_range(parameter),
            ),
        ),
        ParameterValue::Bool(value) => (
            "BoolParam".to_string(),
            format!("id = {id}, name = {name}, default = {}", u8::from(value)),
        ),
        ParameterValue::Choice(value) => (
            format!("EnumParam<{}>", enum_type_name(struct_name, &parameter.id)),
            format!("id = {id}, name = {name}, default = {value}"),
        ),
    }
}

/// Derives a valid Rust field identifier from a stable parameter id.
///
/// Manifest ids are `[a-z0-9._-]`; the separators map to `_`. A leading digit
/// (never produced by the current manifest validator, but cheap to guard) is
/// prefixed so the result is always a legal identifier.
fn field_ident(id: &str) -> String {
    let mut ident: String = id
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect();
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident.insert(0, '_');
    }
    ident
}

/// Derives the generated enum type name for an indexed-choice parameter: the
/// struct name followed by the `PascalCase` of the parameter id. Prefixing with
/// the (unique) struct name keeps the type from colliding with the struct
/// itself or with another generated type in the same module.
fn enum_type_name(struct_name: &str, parameter_id: &str) -> String {
    format!("{struct_name}{}", pascal_ident(parameter_id))
}

/// Derives a `PascalCase` Rust identifier from a stable id by upper-casing the
/// first letter of each `[a-z0-9._-]`-separated segment. A leading digit is
/// prefixed with `_` so the result is always a legal identifier.
fn pascal_ident(id: &str) -> String {
    let mut ident = String::new();
    for segment in id.split(|ch: char| !ch.is_ascii_alphanumeric()) {
        let mut chars = segment.chars();
        if let Some(first) = chars.next() {
            ident.extend(first.to_uppercase());
            ident.push_str(chars.as_str());
        }
    }
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident.insert(0, '_');
    }
    ident
}

/// Builds the truce continuous range literal (e.g. `linear(20, 20000)`,
/// `log(20, 20000)`) for a float parameter, falling back to the unit interval
/// when no numeric range is declared.
fn continuous_range(parameter: &ParameterRecord) -> String {
    match parameter.range {
        Some(range) => {
            let curve = match parameter.distribution {
                ParameterDistribution::Linear => "linear",
                ParameterDistribution::Exponential => "log",
            };
            format!(
                "{curve}({}, {})",
                format_number(range.min),
                format_number(range.max)
            )
        }
        None => "linear(0, 1)".to_string(),
    }
}

/// Builds the truce discrete range literal (e.g. `discrete(1, 8)`) for an
/// integer parameter, rounding the model's float bounds to whole numbers.
fn discrete_range(parameter: &ParameterRecord) -> String {
    match parameter.range {
        Some(range) => format!(
            "discrete({}, {})",
            round_int(range.min),
            round_int(range.max)
        ),
        None => "discrete(0, 1)".to_string(),
    }
}

/// Rounds a model range bound to the nearest integer for a discrete range.
#[allow(clippy::cast_possible_truncation)]
fn round_int(value: f64) -> i64 {
    value.round() as i64
}

/// Maps a parameter's free-form unit label onto a truce `ParamUnit` token.
///
/// Unmappable labels collapse to `none`; the manifest validator already
/// rejects unknown units, so this is a defensive fallback rather than the
/// primary check.
fn map_unit(unit: &str) -> &'static str {
    match unit {
        "dB" | "Db" | "db" => "dB",
        "Hz" | "hz" => "Hz",
        "ms" => "ms",
        "s" => "s",
        "%" => "%",
        "st" => "st",
        "pan" => "pan",
        _ => "none",
    }
}

/// Formats a number as a compact Rust numeric literal: integers without a
/// fractional part, everything else via the shortest round-tripping form.
fn format_number(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{value:.0}")
    } else {
        value.to_string()
    }
}
