// Generated by hawk2ui from the plugin manifest. Do not edit by hand.

use truce::prelude::*;

#[derive(Params)]
pub struct SpikeParams {
    #[param(id = 0, name = "Osc Mix", range = "linear(0, 1)", unit = "none", default = 0.4)]
    pub osc_mix: FloatParam,
    #[param(id = 1, name = "Cutoff", range = "linear(20, 20000)", unit = "Hz", default = 1000)]
    pub filter_cutoff: FloatParam,
}
