// Generated by hawk2ui from the plugin manifest. Do not edit by hand.

use truce::prelude::*;

#[derive(ParamEnum)]
pub enum GeneratedParamsOscShape {
    Sine,
    Saw,
    #[name = "Square / Pulse"]
    SquarePulse,
}

#[derive(Params)]
pub struct GeneratedParams {
    #[param(id = 0, name = "Osc Mix", range = "linear(0, 1)", unit = "none", default = 0.4)]
    pub osc_mix: FloatParam,
    #[param(id = 1, name = "Cutoff", range = "linear(20, 20000)", unit = "Hz", default = 1000)]
    pub filter_cutoff: FloatParam,
    #[param(id = 2, name = "Voices", range = "discrete(1, 8)", unit = "none", default = 4)]
    pub voices: IntParam,
    #[param(id = 3, name = "Bypass", default = 0)]
    pub bypass: BoolParam,
    #[param(id = 4, name = "Osc Shape", default = 1)]
    pub osc_shape: EnumParam<GeneratedParamsOscShape>,
    #[meter]
    pub output_level: MeterSlot,
}
