//! Code generation from the validated parameter model to truce sources.
//!
//! `Hawk2UI` defines parameters once — in the plugin manifest, surfaced as a
//! [`hawk2ui_plugin::ParameterModel`] — and this module emits the Rust
//! `#[derive(Params)]` struct the truce DSP side compiles. A sibling emitter
//! (added with the editor wiring) produces the editor-side TypeScript
//! accessors from the same model, so both sides stay addressable by the same
//! parameter `u32` through truce's [`EditorBridge`](truce_core::editor::EditorBridge).
//!
//! The emitter is pure string generation: it produces truce *source text* and
//! takes no dependency on `truce` itself. Verification that the emitted source
//! actually compiles against truce lives in `tests/params_codegen.rs`, which
//! `include!`s a checked-in golden produced by this emitter.
//!
//! This is the parameter-codegen spike: it covers the `FloatParam` path end to
//! end (emit → compile → bridge read-back). Integer, boolean, and enum
//! parameters, custom curves, meters, and the manifest-to-model bridge land as
//! the model and manifest schema grow to match.

use std::fmt::Write as _;

use hawk2ui_plugin::{ParameterDistribution, ParameterModel, ParameterRecord, ParameterValue};

/// Emits a truce `#[derive(Params)]` struct definition from `model`.
///
/// The returned source is self-contained — it carries its own `use` import —
/// and is intended to be written to a generated module in the author's plugin
/// crate, which depends on the `truce` umbrella crate. Parameters are emitted
/// in declaration order with explicit, declaration-order `id`s so the editor
/// side can address each parameter by the same `u32` through the
/// `EditorBridge`, rather than relying on truce's auto-assignment happening to
/// match.
#[must_use]
pub fn emit_truce_params_struct(struct_name: &str, model: &ParameterModel) -> String {
    let mut out = String::new();
    out.push_str("// Generated by hawk2ui from the plugin manifest. Do not edit by hand.\n\n");
    out.push_str("use truce::prelude::*;\n\n");
    out.push_str("#[derive(Params)]\n");
    let _ = writeln!(out, "pub struct {struct_name} {{");

    let mut next_id: u32 = 0;
    for parameter in &model.parameters {
        emit_param_field(&mut out, next_id, parameter);
        next_id = next_id.saturating_add(1);
    }

    out.push_str("}\n");
    out
}

/// Emits a single `#[param(...)]` field for `parameter` at `id`.
fn emit_param_field(out: &mut String, id: u32, parameter: &ParameterRecord) {
    let field = field_ident(&parameter.id);
    let range = range_literal(parameter);
    let unit = map_unit(&parameter.unit);
    let default = format_number(default_plain(parameter));
    let _ = writeln!(
        out,
        "    #[param(id = {id}, name = {name:?}, range = \"{range}\", unit = \"{unit}\", default = {default})]",
        name = parameter.display_name,
    );
    let _ = writeln!(out, "    pub {field}: FloatParam,");
}

/// Derives a valid Rust field identifier from a stable parameter id.
///
/// Manifest ids are `[a-z0-9._-]`; the separators map to `_`. A leading digit
/// (never produced by the current manifest validator, but cheap to guard) is
/// prefixed so the result is always a legal identifier.
fn field_ident(id: &str) -> String {
    let mut ident: String = id
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect();
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident.insert(0, '_');
    }
    ident
}

/// Builds the truce range literal (e.g. `linear(20, 20000)`) for a parameter.
///
/// The spike emits only continuous ranges; a parameter without a numeric range
/// falls back to the unit interval so the emitted struct still compiles, which
/// the integer/enum work will replace with discrete/enum ranges.
fn range_literal(parameter: &ParameterRecord) -> String {
    match parameter.range {
        Some(range) => {
            let curve = match parameter.distribution {
                ParameterDistribution::Linear => "linear",
                ParameterDistribution::Exponential => "log",
            };
            format!(
                "{curve}({}, {})",
                format_number(range.min),
                format_number(range.max)
            )
        }
        None => "linear(0, 1)".to_string(),
    }
}

/// Maps a parameter's free-form unit label onto a truce `ParamUnit` token.
///
/// Unmappable labels collapse to `none` for the spike; rejecting them with a
/// diagnostic is a model-validation decision deferred to the manifest schema
/// work.
fn map_unit(unit: &str) -> &'static str {
    match unit {
        "dB" | "Db" | "db" => "dB",
        "Hz" | "hz" => "Hz",
        "ms" => "ms",
        "s" => "s",
        "%" => "%",
        "st" => "st",
        "pan" => "pan",
        _ => "none",
    }
}

/// Extracts the plain (denormalized) default value to emit for a parameter.
fn default_plain(parameter: &ParameterRecord) -> f64 {
    match parameter.default_value {
        ParameterValue::Float(value) => value,
        ParameterValue::Bool(value) => f64::from(u8::from(value)),
        ParameterValue::Choice(value) => f64::from(value),
    }
}

/// Formats a number as a compact Rust numeric literal: integers without a
/// fractional part, everything else via the shortest round-tripping form.
fn format_number(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{value:.0}")
    } else {
        value.to_string()
    }
}
